// 9×9 pixel icons for the filters. "X" is solid, "o" is a lighter tone (glass, liquid, pill half),
// "." is empty. Drawn in currentColor so each icon takes its type color.
export const ICONS = {
  all: [
    "XXXX.XXXX",
    "XXXX.XXXX",
    "XXXX.XXXX",
    "XXXX.XXXX",
    ".........",
    "XXXX.XXXX",
    "XXXX.XXXX",
    "XXXX.XXXX",
    "XXXX.XXXX",
  ],
  // capsule
  pharmacology: [
    ".........",
    ".........",
    "..XXooo..",
    ".XXXoooo.",
    ".XXXoooo.",
    ".XXXoooo.",
    "..XXooo..",
    ".........",
    ".........",
  ],
  // heart
  conditions: [
    ".........",
    ".XX...XX.",
    "XXXX.XXXX",
    "XXXXXXXXX",
    "XXXXXXXXX",
    ".XXXXXXX.",
    "..XXXXX..",
    "...XXX...",
    "....X....",
  ],
  // flask
  labs: [
    "...XXX...",
    "...X.X...",
    "...X.X...",
    "..X...X..",
    "..X...X..",
    ".XoooooX.",
    "XoooooooX",
    "XoooooooX",
    "XXXXXXXXX",
  ],
  // clipboard
  fundamentals: [
    "...XXX...",
    ".XXXoXXX.",
    ".X.....X.",
    ".X.XXX.X.",
    ".X.....X.",
    ".X.XXX.X.",
    ".X.....X.",
    ".X.XX..X.",
    ".XXXXXXX.",
  ],
  // "AB"
  abbreviations: [
    ".........",
    ".X..XXX..",
    "X.X.X..X.",
    "X.X.XXX..",
    "XXX.X..X.",
    "X.X.X..X.",
    "X.X.XXX..",
    ".........",
    ".........",
  ],
  // baby bottle
  obstetrics: [
    "....X....",
    "...XXX...",
    "...XXX...",
    "..XXXXX..",
    "..XoooX..",
    "..XoooX..",
    "..XoooX..",
    "..XoooX..",
    "..XXXXX..",
  ],
  // LinkedIn: a filled square with "in" cut out
  linkedin: [
    "XXXXXXXXX",
    "X.XXXXXXX",
    "XXXXXXXXX",
    "X.X....XX",
    "X.X.XX.XX",
    "X.X.XX.XX",
    "X.X.XX.XX",
    "XXXXXXXXX",
    "XXXXXXXXX",
  ],
  // GitHub: a little cat head
  github: [
    "X.......X",
    "XX.....XX",
    "XXXXXXXXX",
    "XX.XXX.XX",
    "XXXXXXXXX",
    ".XXXXXXX.",
    "..XXXXX..",
    "..X.X.X..",
    ".........",
  ],
  // crescent moon (dark mode)
  moon: [
    "...XXXX..",
    "..XXX....",
    ".XXX.....",
    "XXX......",
    "XXX......",
    ".XXX.....",
    "..XXX...X",
    "...XXXXX.",
    ".........",
  ],
  // speaker with sound waves
  soundOn: [
    "....X....",
    "...XX....",
    "XXXXX.X..",
    "XXXXX..X.",
    "XXXXX..X.",
    "XXXXX.X..",
    "...XX....",
    "....X....",
    ".........",
  ],
  // speaker with an X
  soundOff: [
    "....X....",
    "...XX....",
    "XXXXX.X.X",
    "XXXXX..X.",
    "XXXXX.X.X",
    "XXXXX....",
    "...XX....",
    "....X....",
    ".........",
  ],
} satisfies Record<string, string[]>;

export type IconName = keyof typeof ICONS;
