import type { Metadata } from "next";
import L from "@/components/L";

export const metadata: Metadata = {
  title: "Aviso · MyNurseDex",
  description: "MyNurseDex es un apoyo de estudio, no una fuente de indicaciones clínicas.",
};

// Each point in both languages; the full disclaimer linked from the footer.
const POINTS: { en: string; es: string }[] = [
  {
    en: "MyNurseDex is a study aid for nursing students. It is not medical advice and does not replace your instructors, your facility's protocols, a prescriber's order or your own clinical judgment.",
    es: "MyNurseDex es un apoyo de estudio para estudiantes de enfermería. No es consejo médico y no sustituye a sus docentes, los protocolos de su centro, la orden de quien prescribe ni su propio juicio clínico.",
  },
  {
    en: "Entries are drafted with the help of AI from public sources and can contain mistakes. Entries marked “Pending review” have not yet been checked by a person.",
    es: "Las entradas se redactan con ayuda de IA a partir de fuentes públicas y pueden contener errores. Las marcadas como “Pendiente de revisión” aún no han sido revisadas por una persona.",
  },
  {
    en: "Always confirm doses, routes, lab ranges and interventions in a current drug reference, your textbook or your institution's guidelines before using them with a patient.",
    es: "Confirme siempre dosis, vías, valores de laboratorio e intervenciones en una referencia de fármacos actualizada, su libro de texto o las guías de su institución antes de aplicarlos con un paciente.",
  },
  {
    en: "The assistant's answers are generated by AI from MyNurseDex entries and can be wrong or incomplete.",
    es: "Las respuestas del asistente las genera una IA a partir de las entradas de MyNurseDex y pueden ser incorrectas o incompletas.",
  },
  {
    en: "Questions you type into the assistant are sent to an outside AI service (Groq). Don't enter patient names or any information that could identify a patient.",
    es: "Lo que escribe en el asistente se envía a un servicio de IA externo (Groq). No escriba nombres de pacientes ni datos que permitan identificarlos.",
  },
  {
    en: "MyNurseDex is an independent project, not affiliated with the CCSS, the Ministerio de Salud or any university.",
    es: "MyNurseDex es un proyecto independiente, sin relación con la CCSS, el Ministerio de Salud ni ninguna universidad.",
  },
  {
    en: "In an emergency, call 911.",
    es: "En una emergencia, llame al 911.",
  },
];

export default function Aviso() {
  return (
    <article className="max-w-prose">
      <h1 className="font-pixel text-3xl text-ink">
        <L en="Disclaimer" es="Aviso" />
      </h1>
      <p className="mt-4 text-xl leading-relaxed">
        <L en="Study aid only, not clinical guidance." es="Solo para estudio, no es una guía clínica." />
      </p>
      <ul className="mt-6 list-disc space-y-3 pl-5 leading-relaxed">
        {POINTS.map((p) => (
          <li key={p.en}>
            <L en={p.en} es={p.es} />
          </li>
        ))}
      </ul>
    </article>
  );
}
